name: Workflow demo

on: [push, pull_request]

jobs:
  drive:
    strategy:
      matrix:
        device:
        - "iPhone 8 (13.1)"
        - "iPhone 11 Pro Max (13.1)"
      fail-fast: false

    runs-on: macOS-latest

    steps:
    - name: "List all simulators"
      run: "xcrun simctl list devices"

    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun simctl list devices booted |
          grep "${{ matrix.device }}" |
          awk -F '[()]' '{print $2}'
        )
        if [ -z "$UDID" ]; then
          echo "Booting up the simulator..."
          UDID=$(
            xcrun simctl list devices |
            grep "${{ matrix.device }}" |
            awk -F '[()]' '{print $2}'
          )
          xcrun simctl boot "$UDID"
        fi
        echo "Using Simulator with UDID: $UDID"

    - uses: actions/checkout@v1

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: "Run Flutter Driver tests"
      run: "flutter drive --target=test_driver/app.dart"
